In [3]:
# Import Libraries

import pandas as pd
import numpy as np

import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder

from sklearn.linear_model import LinearRegression

from sklearn.metrics import mean_absolute_error
from sklearn.metrics import mean_squared_error
from sklearn.metrics import r2_score

In [30]:
df = pd.read_csv("ENB2012_data.csv")

In [6]:
# Display Dataset
print(df)

       X1     X2     X3      X4   X5  X6   X7  X8     Y1     Y2
0    0.98  514.5  294.0  110.25  7.0   2  0.0   0  15.55  21.33
1    0.98  514.5  294.0  110.25  7.0   3  0.0   0  15.55  21.33
2    0.98  514.5  294.0  110.25  7.0   4  0.0   0  15.55  21.33
3    0.98  514.5  294.0  110.25  7.0   5  0.0   0  15.55  21.33
4    0.90  563.5  318.5  122.50  7.0   2  0.0   0  20.84  28.28
..    ...    ...    ...     ...  ...  ..  ...  ..    ...    ...
763  0.64  784.0  343.0  220.50  3.5   5  0.4   5  17.88  21.40
764  0.62  808.5  367.5  220.50  3.5   2  0.4   5  16.54  16.88
765  0.62  808.5  367.5  220.50  3.5   3  0.4   5  16.44  17.11
766  0.62  808.5  367.5  220.50  3.5   4  0.4   5  16.48  16.61
767  0.62  808.5  367.5  220.50  3.5   5  0.4   5  16.64  16.03

[768 rows x 10 columns]

In [7]:
# First Five Rows
df.head()

     X1     X2     X3      X4   X5  X6   X7  X8     Y1     Y2
0  0.98  514.5  294.0  110.25  7.0   2  0.0   0  15.55  21.33
1  0.98  514.5  294.0  110.25  7.0   3  0.0   0  15.55  21.33
2  0.98  514.5  294.0  110.25  7.0   4  0.0   0  15.55  21.33
3  0.98  514.5  294.0  110.25  7.0   5  0.0   0  15.55  21.33
4  0.90  563.5  318.5  122.50  7.0   2  0.0   0  20.84  28.28

In [8]:
# Last Five Rows
df.tail()

       X1     X2     X3     X4   X5  X6   X7  X8     Y1     Y2
763  0.64  784.0  343.0  220.5  3.5   5  0.4   5  17.88  21.40
764  0.62  808.5  367.5  220.5  3.5   2  0.4   5  16.54  16.88
765  0.62  808.5  367.5  220.5  3.5   3  0.4   5  16.44  17.11
766  0.62  808.5  367.5  220.5  3.5   4  0.4   5  16.48  16.61
767  0.62  808.5  367.5  220.5  3.5   5  0.4   5  16.64  16.03

In [9]:
# Shape of Dataset
print("Shape of Dataset :", df.shape)

Shape of Dataset : (768, 10)

In [10]:
# Column Names
print(df.columns)

Index(['X1', 'X2', 'X3', 'X4', 'X5', 'X6', 'X7', 'X8', 'Y1', 'Y2'], dtype='object')

In [11]:
# Dataset Information
df.info()
# Shows:
# Number of rows
# Number of columns
# Data types
# Null values

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 768 entries, 0 to 767
Data columns (total 10 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   X1      768 non-null    float64
 1   X2      768 non-null    float64
 2   X3      768 non-null    float64
 3   X4      768 non-null    float64
 4   X5      768 non-null    float64
 5   X6      768 non-null    int64
 6   X7      768 non-null    float64
 7   X8      768 non-null    int64
 8   Y1      768 non-null    float64
 9   Y2      768 non-null    float64
dtypes: float64(8), int64(2)
memory usage: 60.1 KB

In [12]:
# Data Types
print(df.dtypes)

X1    float64
X2    float64
X3    float64
X4    float64
X5    float64
X6      int64
X7    float64
X8      int64
Y1    float64
Y2    float64
dtype: object

In [13]:
# Statistical Summary
df.describe()
# Gives:
# Mean
# Median (50%)
# Standard Deviation
# Minimum
# Maximum
# Quartiles

,X1,X2,X3,X4,X5,X6,X7,X8,Y1,Y2
count,768.000000,768.000000,768.000000,768.000000,768.00000,768.000000,768.000000,768.00000,768.000000,768.000000
mean,0.764167,671.708333,318.500000,176.604167,5.25000,3.500000,0.234375,2.81250,22.307195,24.587760
std,0.105777,88.086116,43.626481,45.165950,1.75114,1.118763,0.133221,1.55096,10.090204,9.513306
min,0.620000,514.500000,245.000000,110.250000,3.50000,2.000000,0.000000,0.00000,6.010000,10.900000
25%,0.682500,606.375000,294.000000,140.875000,3.50000,2.750000,0.100000,1.75000,12.992500,15.620000
50%,0.750000,673.750000,318.500000,183.750000,5.25000,3.500000,0.250000,3.00000,18.950000,22.080000
75%,0.830000,741.125000,343.000000,220.500000,7.00000,4.250000,0.400000,4.00000,31.667500,33.132500
max,0.980000,808.500000,416.500000,220.500000,7.00000,5.000000,0.400000,5.00000,43.100000,48.030000

In [14]:
# Check Missing Values
df.isnull().sum()

X1    0
X2    0
X3    0
X4    0
X5    0
X6    0
X7    0
X8    0
Y1    0
Y2    0
dtype: int64

In [15]:
# Total Missing Values
print("Total Missing Values =", df.isnull().sum().sum())

Total Missing Values = 0

In [16]:
# Duplicate Rows
print("Duplicate Rows =", df.duplicated().sum())

Duplicate Rows = 0

In [29]:
# Remove Duplicate Rows (if any)
df = df.drop_duplicates()

In [25]:
# Display Random Records
df.sample(10)

       X1     X2     X3      X4   X5  X6    X7  X8     Y1     Y2
302  0.82  612.5  318.5  147.00  7.0   4  0.25   1  26.97  27.25
380  0.62  808.5  367.5  220.50  3.5   2  0.25   2  14.34  15.32
698  0.74  686.0  245.0  220.50  3.5   4  0.40   4  14.32  16.90
193  0.98  514.5  294.0  110.25  7.0   3  0.10   4  24.23  25.72
91   0.64  784.0  343.0  220.50  3.5   5  0.10   1  15.21  19.32
526  0.62  808.5  367.5  220.50  3.5   4  0.25   5  14.16  14.61
419  0.69  735.0  294.0  220.50  3.5   5  0.25   3  12.12  15.17
653  0.71  710.5  269.5  220.50  3.5   3  0.40   3  14.03  15.47
393  0.86  588.0  294.0  147.00  7.0   3  0.25   3  29.40  32.93
722  0.98  514.5  294.0  110.25  7.0   4  0.40   5  32.21  33.76

In [26]:
# Check Unique Values
for column in df.columns:
    print(column)
    print(df[column].unique())
    print("-"*50)

X1
[0.98 0.9  0.86 0.82 0.79 0.76 0.74 0.71 0.69 0.66 0.64 0.62]
--------------------------------------------------
X2
[514.5 563.5 588.  612.5 637.  661.5 686.  710.5 735.  759.5 784.  808.5]
--------------------------------------------------
X3
[294.  318.5 343.  416.5 245.  269.5 367.5]
--------------------------------------------------
X4
[110.25 122.5  147.   220.5 ]
--------------------------------------------------
X5
[7.  3.5]
--------------------------------------------------
X6
[2 3 4 5]
--------------------------------------------------
X7
[0.   0.1  0.25 0.4 ]
--------------------------------------------------
X8
[0 1 2 3 4 5]
--------------------------------------------------
Y1
[15.55  20.84  21.46  20.71  19.68  19.5   19.95  19.34  18.31  17.05
 17.41  16.95  15.98  28.52  29.9   29.63  28.75  24.77  23.93   6.07
  6.05   6.01   6.04   6.37   6.4    6.366  6.85   6.79   6.77   6.81
  7.18   7.1   10.85  10.54  10.77  10.56   8.6    8.49   8.45   8.5
 24.58  24.63  24.59  29.03  29.87  29.14  28.09  26.28  26.91  26.37
 25.27  23.53  24.03  23.54  22.58  35.56  37.12  36.9   35.94  32.96
 32.12  32.94  32.21  10.36  10.43  10.39  10.71  10.8   10.7   10.75
 11.11  11.13  11.09  11.16  11.68  11.69  11.7   15.41  15.2   15.42
 15.21  12.96  12.97  12.93  13.02  24.29  24.31  24.13  24.25  28.88
 29.68  28.83  27.9   26.48  27.02  26.33  25.36  23.75  24.23  23.67
 22.79  35.65  37.26  36.97  36.03  33.16  32.4   33.12  32.41  10.42
 10.46  10.32  10.45  10.64  10.72  10.55  10.68  11.45  11.46  11.32
 11.49  11.42  11.33  11.43  15.18  15.34  15.19  12.88  13.    13.04
 24.28  24.4   24.11  24.35  28.07  29.01  29.62  29.05  25.41  26.47
 26.89  26.46  22.93  23.84  24.17  23.87  35.78  35.48  36.7   32.52
 33.28  32.33  33.24  10.34  10.35  10.38  11.22  11.1   11.14  11.59
 11.6   11.53  11.61  15.16  15.36  15.12  12.68  12.63  12.71  12.73
 24.38  24.04  24.32  29.06  28.05  28.86  29.79  26.44  25.37  27.03
 23.8   22.8   23.59  24.24  36.86  35.89  35.45  37.1   33.08  32.38
 33.09  32.31  10.08  10.15  10.07  10.14  10.66  10.53  11.18  11.07
 11.2   11.44  15.4   15.32  12.85  24.33  24.26  29.83  29.08  28.03
 29.02  26.45  24.37  23.89  22.89  23.86  37.03  36.71  36.77  33.21
 32.46  33.27  10.47  10.37  10.78  10.67  13.69  11.21  11.38  11.34
 15.37  12.59  12.74  12.8   12.62  28.15  28.37  28.41  32.68  33.48
 32.84  32.    29.54  30.05  29.6   28.66  26.84  27.27  26.97  26.19
 38.67  40.03  39.86  39.04  36.96  36.13  36.91  36.43  12.43  12.5
 12.41  12.45  12.57  12.65  12.78  12.72  13.17  13.18  17.5   17.35
 17.52  17.37  15.09  15.08  28.67  28.57  28.18  28.6   31.66  29.34
 29.27  28.4   25.74  25.98  25.38  24.94  38.57  40.19  39.97  38.98
 36.95  36.28  36.45  12.35  12.16  12.3   12.33  12.29  12.2   12.49
 12.87  12.95  13.05  12.77  17.14  16.84  17.02  17.11  14.34  14.66
 14.6   28.56  28.17  28.63  31.63  32.29  29.4   29.43  29.07  24.7
 25.48  25.17  38.35  39.81  39.83  35.99  36.59  35.64  36.52  11.8
 12.03  11.98  12.28  12.1   12.19  12.34  12.46  12.31  12.12  13.01
 12.84  16.83  16.93  16.66  16.86  13.91  13.95  13.99  28.7   28.55
 28.62  32.67  31.69  32.07  29.47  28.42  29.88  25.66  24.96  25.43
 26.    40.    38.84  38.33  40.12  36.81  36.26  12.32  12.18  12.36
 12.17  12.91  12.67  12.86  12.92  16.99  16.69  16.56  16.62  14.33
 14.61  14.65  28.69  28.58  28.61  33.13  31.53  29.71  29.09  28.31
 29.39  25.7   24.6   25.49  39.89  39.01  38.65  35.69  36.64  36.06
 11.67  11.64  12.02  12.27  12.25  12.47  12.82  16.73  16.76  16.92
 13.68  14.16  13.86  32.26  32.49  32.53  36.47  37.24  36.66  35.96
 31.89  32.39  32.09  31.29  29.22  29.91  29.53  28.65  41.4   42.62
 42.5   41.67  40.78  40.71  40.43  14.52  14.5   14.55  14.51  14.58
 14.7   14.42  15.23  19.52  19.36  19.48  19.42  17.17  32.82  32.71
 32.24  32.72  35.84  36.57  32.48  32.74  32.13  31.64  28.95  29.49
 28.64  28.01  41.64  43.1   42.74  41.92  40.15  40.57  40.42  14.54
 14.45  14.18  14.4   14.71  14.75  14.62  15.29  15.3   19.2   18.88
 18.9   19.12  17.23  17.26  17.15  32.69  32.23  32.75  34.24  34.95
 35.05  34.29  31.28  32.05  31.84  29.67  28.91  41.26  41.3   42.49
 42.08  39.32  39.84  38.89  39.68  13.97  14.22  14.1   13.78  14.07
 14.03  13.94  14.32  14.56  14.08  14.72  14.9   18.48  18.71  18.46
 16.47  16.35  16.55  16.74  32.85  35.73  35.4   32.15  28.93  29.52
 42.77  41.73  41.32  42.96  40.68  40.4   40.6   40.11  14.37  14.48
 14.44  14.47  14.53  19.06  19.13  19.    18.84  16.44  16.9   16.94
 16.77  32.73  35.67  35.01  34.72  35.24  31.81  31.12  32.06  30.
 29.5   29.92  42.11  41.96  41.09  40.79  38.82  39.72  39.31  14.41
 14.19  14.17  14.39  12.76  12.42  14.12  14.28  14.21  14.96  14.92
 17.69  18.19  18.16  17.88  16.54  16.48  16.64 ]
--------------------------------------------------
Y2
[21.33 28.28 25.38 25.16 29.6  27.3  21.97 23.49 27.87 23.77 21.46 21.16
 24.93 37.73 31.27 30.93 39.44 29.79 29.68 29.4  10.9  11.19 10.94 11.17
 11.27 11.72 11.29 11.67 11.74 12.05 11.73 11.93 12.4  12.23 12.14 16.78
 16.8  16.75 16.67 12.07 12.22 12.08 12.04 26.47 26.37 26.44 26.29 32.92
 29.87 29.58 34.33 30.89 25.6  27.03 31.73 27.31 24.91 24.61 28.51 41.68
 35.28 34.43 43.33 33.87 34.07 34.14 33.67 13.43 13.71 13.48 13.7  13.8
 14.28 13.87 14.27 14.61 14.3  14.45 13.9  13.72 13.88 13.65 19.37 19.43
 19.34 19.32 14.34 14.5  14.33 25.95 25.63 26.13 25.89 32.54 29.44 29.36
 34.2  30.91 27.36 31.9  27.38 25.02 24.8  28.79 41.07 34.62 42.86 33.91
 34.17 33.78 13.39 13.57 13.79 13.67 14.11 14.21 13.2  13.54 13.32 13.51
 14.86 14.75 15.   14.74 19.23 19.3  14.37 14.57 14.24 25.68 26.02 25.84
 26.14 32.85 30.08 29.67 31.01 25.9  27.4  28.68 27.54 25.35 43.12 41.22
 35.1  34.29 33.85 34.11 34.48 34.5  13.6  13.36 13.49 14.14 13.77 14.44
 14.67 14.4  13.46 13.59 13.83 19.14 19.18 19.29 14.09 14.23 13.89 25.91
 25.72 26.18 25.87 29.34 32.83 29.92 27.17 31.76 31.06 25.81 28.61 27.57
 34.25 43.3  41.86 35.29 33.62 33.89 34.05 13.21 13.53 14.12 14.2  14.29
 14.49 14.42 14.73 14.83 19.24 19.25 19.42 19.48 14.47 25.64 25.98 25.88
 29.82 29.52 34.45 33.01 25.82 27.33 32.04 31.28 25.11 24.77 28.88 27.69
 34.99 34.18 43.14 41.26 34.35 33.64 33.88 13.44 13.5  14.18 13.75 14.26
 14.55 14.46 14.39 14.54 14.81 14.65 14.87 19.26 13.97 13.99 14.15 29.28
 29.49 36.12 33.17 32.71 37.58 33.98 30.12 34.73 30.17 27.84 27.25 31.39
 43.8  37.81 36.85 45.52 37.45 36.62 15.19 15.5  15.28 15.42 15.85 15.44
 15.81 15.21 15.63 15.48 15.78 16.39 16.27 16.19 21.13 21.19 21.09 21.08
 15.77 15.95 15.76 29.62 29.69 30.18 30.02 35.56 32.64 32.77 37.72 33.37
 27.89 29.9  34.52 28.27 26.96 26.72 29.88 43.86 37.41 36.77 45.97 36.87
 37.35 37.28 36.81 15.1  15.18 14.91 15.4  14.94 15.32 15.52 15.66 15.99
 15.89 16.22 15.87 20.47 20.56 20.48 20.43 15.64 15.14 15.3  29.43 29.78
 30.1  30.19 36.35 32.46 33.52 32.93 28.38 28.77 27.76 26.95 26.41 45.13
 43.66 37.76 36.07 36.44 37.29 14.72 14.76 14.92 15.57 14.38 15.17 15.53
 15.8  16.14 16.26 19.87 20.03 20.46 20.28 14.89 14.96 14.35 29.61 29.59
 32.12 37.12 36.16 33.16 29.45 34.19 33.93 28.31 26.3  28.76 27.34 36.26
 45.48 44.16 37.26 37.2  36.76 37.05 37.51 15.24 15.03 15.35 15.09 15.2
 15.37 15.73 15.83 16.13 15.59 16.17 19.65 19.76 20.37 19.9  15.41 15.56
 15.07 15.38 29.53 29.77 30.   30.2  32.25 32.   37.19 35.62 28.02 34.15
 33.47 26.53 26.08 29.31 28.14 37.54 36.66 45.28 43.73 36.93 37.01 35.73
 36.15 14.48 14.58 14.03 15.27 14.71 15.23 14.97 15.22 14.6  16.03 16.06
 20.13 20.01 20.19 20.29 33.34 33.04 39.28 36.38 35.92 40.99 35.99 30.66
 31.7  36.73 31.71 29.13 28.99 33.54 45.29 39.07 38.35 46.94 39.55 40.85
 40.63 39.48 16.94 17.25 17.03 17.1  17.51 17.12 17.47 16.5  17.   16.87
 17.2  18.14 18.03 17.95 22.72 22.73 22.53 17.21 17.15 32.96 33.13 33.94
 35.39 34.94 40.66 35.48 30.53 32.28 36.86 30.34 27.93 28.95 45.59 39.41
 38.84 48.03 40.4  40.47 39.7  16.43 16.93 16.99 16.77 17.37 17.27 16.44
 17.01 17.23 17.22 17.85 17.89 18.36 18.15 21.72 22.07 22.09 21.93 17.36
 17.38 16.86 32.78 33.24 33.86 34.   35.04 33.82 33.31 35.22 34.7  30.11
 31.6  32.43 30.65 29.64 46.44 44.18 38.81 38.23 38.17 38.48 39.66 40.1
 16.08 15.39 16.57 16.6  16.11 15.47 16.7  16.1  16.35 15.84 17.02 17.04
 17.63 18.1  18.22 20.78 20.72 21.54 21.53 16.9  17.14 16.56 16.   32.95
 33.06 33.95 39.92 39.22 36.1  31.53 36.2  36.21 31.   28.2  32.35 31.14
 28.43 38.33 47.59 46.23 39.56 40.36 39.67 39.85 40.77 16.61 16.74 17.32
 16.85 17.74 16.81 16.88 17.39 17.86 17.82 18.24 21.68 22.25 22.49 16.79
 16.58 32.88 33.23 33.76 34.01 33.14 38.79 37.27 31.2  35.71 29.93 29.56
 33.84 38.56 37.7  47.01 44.87 39.37 39.8  37.79 38.18 16.69 16.62 15.33
 15.31 16.63 16.54 17.64 17.79 17.55 18.06 20.82 20.21 20.71 21.4  17.11]
--------------------------------------------------

In [27]:
# Count Unique Values
df.nunique()

X1     12
X2     12
X3      7
X4      4
X5      2
X6      4
X7      4
X8      6
Y1    587
Y2    636
dtype: int64

In [28]:
# Correlation Matrix (Numerical Only)
df.corr(numeric_only=True)

,X1,X2,X3,X4,X5,X6,X7,X8,Y1,Y2
X1,1.000000e+00,-9.919015e-01,-2.037817e-01,-8.688234e-01,8.277473e-01,4.678592e-17,-2.960552e-15,-7.107006e-16,0.622272,0.634339
X2,-9.919015e-01,1.000000e+00,1.955016e-01,8.807195e-01,-8.581477e-01,-3.459372e-17,3.636925e-15,2.438409e-15,-0.658120,-0.672999
X3,-2.037817e-01,1.955016e-01,1.000000e+00,-2.923165e-01,2.809757e-01,-2.429499e-17,-8.567455e-17,2.067384e-16,0.455671,0.427117
X4,-8.688234e-01,8.807195e-01,-2.923165e-01,1.000000e+00,-9.725122e-01,-5.830058e-17,-1.759011e-15,-1.078071e-15,-0.861828,-0.862547
X5,8.277473e-01,-8.581477e-01,2.809757e-01,-9.725122e-01,1.000000e+00,4.492205e-17,1.489134e-17,-2.920613e-17,0.889430,0.895785
X6,4.678592e-17,-3.459372e-17,-2.429499e-17,-5.830058e-17,4.492205e-17,1.000000e+00,-9.406007e-16,-2.549352e-16,-0.002587,0.014290
X7,-2.960552e-15,3.636925e-15,-8.567455e-17,-1.759011e-15,1.489134e-17,-9.406007e-16,1.000000e+00,2.129642e-01,0.269842,0.207505
X8,-7.107006e-16,2.438409e-15,2.067384e-16,-1.078071e-15,-2.920613e-17,-2.549352e-16,2.129642e-01,1.000000e+00,0.087368,0.050525
Y1,6.222719e-01,-6.581199e-01,4.556714e-01,-8.618281e-01,8.894305e-01,-2.586763e-03,2.698417e-01,8.736846e-02,1.000000,0.975862
Y2,6.343391e-01,-6.729989e-01,4.271170e-01,-8.625466e-01,8.957852e-01,1.428960e-02,2.075050e-01,5.052512e-02,0.975862,1.000000